---
version: 2
plan:
  project-key: UIGOV
  key: CUWC
  name: ci-uigov-web-components

stages:
  - Build and Test Stage:
      jobs:
        - build-apps-libs-and-storybook
        - perform-all-unit-tests
        - perform-all-web-tests
        - e2e-tests-storybook-1
        - e2e-tests-storybook-2
        - e2e-tests-storybook-3

build-apps-libs-and-storybook:
  requirements: &requirements
    - Docker
    - Git
    - REMOTE_ONLY
  tasks:
    - clean
    - script: &checkout-script |
        echo 'clone repo'
        git clone --branch feature/UIG-2466-build https://github.com/milieuinfo/uigov-web-components.git
        git fetch --tags
    - script: . ./uigov-web-components/resources/ci/scripts/build-apps-libs-and-storybook-docker.sh

perform-all-unit-tests:
  requirements: *requirements
  tasks:
    - clean
    - script: *checkout-script
    - script: . ./uigov-web-components/resources/ci/scripts/perform-all-unit-tests-docker.sh

perform-all-web-tests:
  requirements: *requirements
  tasks:
    - clean
    - script: *checkout-script
    - script: . ./uigov-web-components/resources/ci/scripts/perform-all-web-tests-docker.sh

e2e-tests-storybook-1:
  requirements: *requirements
  tasks:
    - clean
    - script: *checkout-script
    - script:
        interpreter: /bin/bash
        file: e2e-tests-storybook-docker.sh
        argument: a
        working-dir: uigov-web-components\resources\ci\scripts

e2e-tests-storybook-2:
  requirements: *requirements
  tasks:
    - clean
    - script: *checkout-script
    - script: |
        export STORYBOOK_INDEX="2"
        . ./uigov-web-components/resources/ci/scripts/e2e-tests-storybook-docker.sh

e2e-tests-storybook-3:
  requirements: *requirements
  tasks:
    - clean
    - script: *checkout-script
    - script: |
        export STORYBOOK_INDEX=3
        . ./uigov-web-components/resources/ci/scripts/e2e-tests-storybook-docker.sh
