version: 2
plan:
  project-key: UIGOV
  key: CUWC
  name: ci-uigov-web-components

stages:
  - Build and Test Stage:
      jobs:
        - build-apps-libs-and-storybook
        - perform-all-unit-tests
        - perform-all-web-tests
        - e2e-test-storybook-1

build-apps-libs-and-storybook:
  requirements:
    - Docker
    - Git
    - REMOTE_ONLY
  tasks:
    - clean
    - script: |
        echo 'clone repo'
        git clone --branch feature/UIG-2466-build https://github.com/milieuinfo/uigov-web-components.git
        git fetch --tags
    - script: |
        echo 'build-apps-libs-and-storybook'
        export BUILD_SCRIPT=uigov-web-components/resources/ci/build-apps-libs-and-storybook.sh
        cd uigov-web-components/resources/ci
        echo 'docker-compose up -V'
        docker-compose up -V --abort-on-container-exit --exit-code-from build

perform-all-unit-tests:
  requirements:
    - Docker
    - Git
    - REMOTE_ONLY
  tasks:
    - clean
    - script: |
        echo 'clone repo'
        git clone --branch feature/UIG-2466-build https://github.com/milieuinfo/uigov-web-components.git
        git fetch --tags
    - script: |
        echo 'perform-all-unit-tests'
        export BUILD_SCRIPT=uigov-web-components/resources/ci/perform-all-unit-tests.sh
        cd uigov-web-components/resources/ci
        echo 'docker-compose up -V'
        docker-compose up -V --abort-on-container-exit --exit-code-from build

perform-all-web-tests:
  requirements:
    - Docker
    - Git
    - REMOTE_ONLY
  tasks:
    - clean
    - script: |
        echo 'clone repo'
        git clone --branch feature/UIG-2466-build https://github.com/milieuinfo/uigov-web-components.git
        git fetch --tags
    - script: |
        echo 'perform-all-web-tests'
        export BUILD_SCRIPT=uigov-web-components/resources/ci/perform-all-web-tests.sh
        cd uigov-web-components/resources/ci
        echo 'docker-compose up -V'
        docker-compose up -V --abort-on-container-exit --exit-code-from build

e2e-test-storybook-1:
  requirements:
    - Docker
    - Git
    - REMOTE_ONLY
  tasks:
    - clean
    - script: |
        echo 'clone repo'
        git clone --branch feature/UIG-2466-build https://github.com/milieuinfo/uigov-web-components.git
        git fetch --tags
    - script: |
        echo 'perform-all-web-tests'
        export BUILD_SCRIPT=uigov-web-components/resources/ci/e2e-test-storybook.sh
        cd uigov-web-components/resources/ci
        echo 'docker-compose up -V'
        docker-compose up -V --abort-on-container-exit --exit-code-from build
