version: 2
plan:
  project-key: UIGOV
  key: CUWC
  name: ci-uigov-web-components

stages:
  - Stage 1:
      jobs:
        - perform-all-unit-tests
        - perform-all-web-tests
        - build-apps-libs-and-storybook

perform-all-unit-tests:
  tasks:
    - checkout:
        repository: uigov-web-components
        path: uigov-web-components
        force-clean-build: true
    - script:
        - echo 'perform-all-unit-tests'
        - npm ci
        - npx nx run-many --all --target=test --parallel --maxParallel=4 --skip-nx-cache

perform-all-web-tests:
  tasks:
    - script:
        - echo 'perform-all-web-tests'

build-apps-libs-and-storybook:
  tasks:
    - script:
        - echo 'build-apps-libs-and-storybook'
