version: 2
plan:
  project-key: UIGOV
  key: CUWC
  name: ci-uigov-web-components

stages:
  - Stage 1:
      jobs:
        - perform-all-unit-tests
        - perform-all-web-tests

perform-all-unit-tests:
  requirements:
    - Docker
    - Git
    - REMOTE_ONLY
  tasks:
    - script: |
        echo 'remove old git folder'
        rm -rf .git
        echo 'clone repo'
        git clone --branch feature/UIG-2466-build https:/github.com/milieuinfo/uigov-web-components.git
        git fetch --tags
        cd uigov-web-components
    - script: |
        echo 'perform-all-unit-tests'
        export BUILD_SCRIPT=uigov-web-components/resources/ci/perform-all-unit-tests.sh
        cd uigov-web-components/resources/ci
        echo 'docker-compose up -V'
        docker-compose up -V

perform-all-web-tests:
  tasks:
    - script:
        - echo 'perform-all-web-tests'
