---
version: 2
plan:
  project-key: UIGOV
  key: CUWC
  name: ci-uigov-web-components

stages:
  - Build and Test Stage:
      jobs:
        - build-apps-libs-and-storybook
        - perform-all-unit-tests
        - perform-all-web-tests
        - e2e-tests-storybook-1
        - e2e-tests-storybook-2
        - e2e-tests-storybook-3
        - e2e-tests-storybook-4
        - e2e-tests-storybook-5
        - e2e-tests-storybook-6

build-apps-libs-and-storybook:
  requirements: &requirements
    - Docker
    - Git
    - REMOTE_ONLY
  tasks:
    - clean
    - script: &checkout-script |
        echo 'bamboo.planRepository.branchDisplayName ${bamboo.planRepository.branchDisplayName}'
        echo 'bamboo.planRepository.branch ${bamboo.planRepository.branch}'
        echo 'bamboo.planRepository.repositoryUrl ${bamboo.planRepository.repositoryUrl}'
        echo 'clone repo'
        git clone --branch feature/UIG-2466-build https://github.com/milieuinfo/uigov-web-components.git
        git fetch --tags
    - script: bash ./uigov-web-components/resources/ci/scripts/build-apps-libs-and-storybook-docker.sh
  artifacts:
    - name: dist-build-apps-libs-and-storybook
      location: uigov-web-components/dist
      pattern: '**/*.*'
      shared: true

perform-all-unit-tests:
  requirements: *requirements
  tasks:
    - clean
    - script: *checkout-script
    - script: bash ./uigov-web-components/resources/ci/scripts/perform-all-unit-tests-docker.sh
  artifacts:
    - name: dist-perform-all-unit-tests
      location: uigov-web-components/dist
      pattern: '**/*.*'
      shared: true

perform-all-web-tests:
  requirements: *requirements
  tasks:
    - clean
    - script: *checkout-script
    - script: bash ./uigov-web-components/resources/ci/scripts/perform-all-web-tests-docker.sh
  artifacts:
    - name: dist-perform-all-web-tests
      location: uigov-web-components/dist
      pattern: '**/*.*'
      shared: true

e2e-tests-storybook-1:
  requirements: *requirements
  tasks:
    - clean
    - script: *checkout-script
    - script: bash ./uigov-web-components/resources/ci/scripts/e2e-tests-storybook-docker.sh 1
  artifacts:
    - name: dist-e2e-tests-storybook-1
      location: uigov-web-components/dist
      pattern: '**/*.*'
      shared: true

e2e-tests-storybook-2:
  requirements: *requirements
  tasks:
    - clean
    - script: *checkout-script
    - script: bash ./uigov-web-components/resources/ci/scripts/e2e-tests-storybook-docker.sh 2
  artifacts:
    - name: dist-e2e-tests-storybook-2
      location: uigov-web-components/dist
      pattern: '**/*.*'
      shared: true

e2e-tests-storybook-3:
  requirements: *requirements
  tasks:
    - clean
    - script: *checkout-script
    - script: bash ./uigov-web-components/resources/ci/scripts/e2e-tests-storybook-docker.sh 3
  artifacts:
    - name: dist-e2e-tests-storybook-3
      location: uigov-web-components/dist
      pattern: '**/*.*'
      shared: true

e2e-tests-storybook-4:
  requirements: *requirements
  tasks:
    - clean
    - script: *checkout-script
    - script: bash ./uigov-web-components/resources/ci/scripts/e2e-tests-storybook-docker.sh 4
  artifacts:
    - name: dist-e2e-tests-storybook-4
      location: uigov-web-components/dist
      pattern: '**/*.*'
      shared: true

e2e-tests-storybook-5:
  requirements: *requirements
  tasks:
    - clean
    - script: *checkout-script
    - script: bash ./uigov-web-components/resources/ci/scripts/e2e-tests-storybook-docker.sh 5
  artifacts:
    - name: dist-e2e-tests-storybook-5
      location: uigov-web-components/dist
      pattern: '**/*.*'
      shared: true

e2e-tests-storybook-6:
  requirements: *requirements
  tasks:
    - clean
    - script: *checkout-script
    - script: bash ./uigov-web-components/resources/ci/scripts/e2e-tests-storybook-docker.sh 6
  artifacts:
    - name: dist-e2e-tests-storybook-6
      location: uigov-web-components/dist
      pattern: '**/*.*'
