version: "3.9"
services:
    build:
        image: cypress/browsers:node18.12.0-chrome107
        container_name: uigov-web-components-build
        command: bash uigov-web-components/resources/ci/build-and-release.sh
        volumes:
            - ${HOME:-.}/.npmrc:/root/.npmrc:ro
            - ./../..:/uigov-web-components
            - /uigov-web-components/node_modules
        environment:
            - secret_github_token=$secret_github_token
            - test_token=$test_token
            - GITHUB_TOKEN=$GITHUB_TOKEN
